# docker-compose.yml
version: "3.8"

services:
  app:
    build: .
    container_name: fastapi_app
    ports:
      - "8000:80"
    environment:
      - SETTINGS_MODE=${SETTINGS_MODE}
    depends_on:
      - redis

  redis:
    image: "redis:latest"
    container_name: redis
    ports:
      - "6379:6379"
