name: Test and Lint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint pytest requests fastapi uvicorn httpx
    - name: Start Uvicorn server
      run: |
        nohup uvicorn main:app --host 127.0.0.1 --port 8000 &
        sleep 3  # Wait for the server to start
    - name: Run tests with pytest
      run: |
        pytest tests
    - name: Stop Uvicorn server
      if: always()
      run: |
        pkill -f "uvicorn main:app"
