# .github/workflows/ci.yml
name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements_dev.txt
    - name: Lint with Pylint
      run: |
        pylint main.py atm_repository_redis.py atm_repository_json_file.py atm_service.py tests
    - name: Format with Black
      run: |
        black --check .
    - name: Start Uvicorn server
      run: |
        SETTINGS_MODE=text uvicorn main:app --host 127.0.0.1 --port 8000 &
        sleep 10  # Wait for the server to start
    - name: Run tests with coverage
      run: |
        SETTINGS_MODE=text pytest --cov=./ --cov-report=xml
    - name: Stop Uvicorn server
      if: always()
      run: |
        pkill -f "uvicorn main:app"

  coverage:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements_dev.txt
    - name: Start Uvicorn server
      run: |
        SETTINGS_MODE=text uvicorn main:app --host 127.0.0.1 --port 8000 &
        sleep 10  # Wait for the server to start
    - name: Run tests with coverage
      run: |
        SETTINGS_MODE=text pytest tests --cov=./ --cov-report=xml
    - name: Check coverage
      run: |
        coverage report --fail-under=75
#    - name: Upload coverage to Codecov
#      uses: codecov/codecov-action@v2
#      with:
#        files: ./coverage.xml
#        flags: unittests
#        name: codecov-umbrella
#        fail_ci_if_error: true
    - name: Stop Uvicorn server
      if: always()
      run: |
        pkill -f "uvicorn main:app"
